### ISSUE TITLE
"ImportError: no module named energenie" when starting from init

### ISSUE THREAD

**Issue by PJBentham** [penguintutor/pi-power#1]
This works when starting from the directory but when I try to start automatically I get the above error?

**Comment by penguintutor** [comment]
That is a message issued by Python to say it cannot find the module. 
That is a module that is installable for the Raspberry Pi using PIP. In particular as the code is written for Python 3 you will need to install the PIP3 version.

sudo pip3 install energenie

If you installed version 2 or used the apt-get version then this may explain the error.
